### ISSUE TITLE
appt needs to be viewed even after a patient has checked out

### ISSUE THREAD

**Issue by jeffypie369** [CS2103-AY1819S1-W14-3/main#191]

**Comment by yuntongzhang** [comment]
After discussion, the solution is:
1. Differentiate the error message between when a patient really does not exist, and when a person is checked out. This needs to be implemented by adding a check on all the commands and decide which error message to be displayed.
2. Mention in the UserGuide under `checkout` section: after a patient has been checked out, all commands except `checkin` will not be valid on this patient.
