### ISSUE TITLE
As a counter staff, I can check out patients

### ISSUE THREAD

**Issue by jeffypie369** [CS2103-AY1819S1-W14-3/main#66]
Remove a patient from the patient queue after this patient checks out of the hospital.

**Comment by yuntongzhang** [comment]
Work in progress.

- [ ] Add an internal list of `checkedOutPerson` into `AddressBook`
- [ ] Modify the XML tags to support `checkOutPerson`
- [ ] Add a `checkout` command which handles the logic of moving a `Person` from the normal `Person List` to the `checkedOutPerson List`
- [ ] Add a `return` command to 'checkin' the returned patients. The command will direct user to use `checkin` if the patient has not visited the clinic before.
- [ ] Add relevant test
- [ ] Update UserGuide
- [ ] Update DeveloperGuide
